"""Per-file classification of vault artifacts (T2.3.1 D-01/D-02/D-03).

Every file generated by `wolta init` is classified as one of three policies.
The unit of classification is the file (or a glob), not the directory, because
TEMPLATES/ and AI-SYSTEM/SKILLS/ hold files of mixed provenance. Anything not
listed is user-owned (fail-safe default).
"""

import fnmatch
from enum import Enum


class Policy(str, Enum):
    MANAGED = "managed"                  # full-file, checksum-guarded
    MANAGED_SECTION = "managed-section"  # only marker-delimited blocks
    USER_OWNED = "user-owned"            # never touched


# Exact relative paths (highest precedence).
MANIFEST = {
    # Tier 1 - managed full-file
    "README.md": Policy.MANAGED,
    "raw/README.md": Policy.MANAGED,
    "AI-SYSTEM/SKILLS/bootstrap-generate.md": Policy.MANAGED,
    "AI-SYSTEM/SKILLS/raw-ingest.md": Policy.MANAGED,
    "AI-SYSTEM/SKILLS/INGEST-PROTOCOL.md": Policy.MANAGED,
    "AI-SYSTEM/SKILLS/source-files.md": Policy.MANAGED,
    "TEMPLATES/template-source-adapter.md": Policy.MANAGED,
    # Tier 2 - managed-section
    "CLAUDE.md": Policy.MANAGED_SECTION,
    "DESIGN.md": Policy.MANAGED_SECTION,
}

# Glob patterns (checked after exact matches).
# User-created adapters: source-*.md EXCEPT source-files.md (which is exact above).
GLOBS = [
    ("AI-SYSTEM/SKILLS/source-*.md", Policy.USER_OWNED),
]

# Fail-safe: anything unclassified is user-owned (never destructive).
DEFAULT = Policy.USER_OWNED


def classify(rel_path: str) -> Policy:
    """Return the policy for a vault-relative path.

    Precedence: exact match > first matching glob > default (user-owned).
    """
    rel = str(rel_path).replace("\\", "/")
    if rel in MANIFEST:
        return MANIFEST[rel]
    for pattern, policy in GLOBS:
        if fnmatch.fnmatch(rel, pattern):
            return policy
    return DEFAULT
